# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target ‘侧滑’ do
pod 'SDWebImage'
pod 'AFNetworking','~> 2.0'
pod 'Masonry'
pod ‘SWRevealViewController’

end
